### ISSUE TITLE
how to make plotnine work ? (if ever possible)

### ISSUE THREAD

**Issue by stonebig** [rstudio/shinylive#29]
how can I "redirect" Matplotlib so plotnine do work ?

````
import pandas as pd
import numpy as np

from plotnine import *

df = pd.DataFrame({
    'variable': ['gender', 'gender', 'age', 'age', 'age', 'income', 'income', 'income', 'income'],
    'category': ['Female', 'Male', '1-24', '25-54', '55+', 'Lo', 'Lo-Med', 'Med', 'High'],
    'value': [60, 40, 50, 30, 20, 10, 25, 25, 40],
})
df['variable'] = pd.Categorical(df['variable'], categories=['gender', 'age', 'income'])
df['category'] = pd.Categorical(df['category'], categories=df['category'])

 (ggplot(df, aes(x='variable', y='value', fill='category'))
 + geom_col()
)
````

gives this
````

/lib/python3.10/site-packages/plotnine/ggplot.py:862: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
<ggplot: (-2141397610)>
>>> /lib/python3.10/site-packages/plotnine/ggplot.py:862: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
````

**Comment by wch** [comment]
Are you trying to run this in the shinylive.io terminal, or in a Shiny app?

**Comment by stonebig** [comment]
In the shinylive.io website

**Comment by wch** [comment]
Sorry for taking so long to reply! The shinylive.io web interface _does_ support plotnine, but it must be in the context of a Shiny app.

However, if you're trying to run plotnine code (or matplotlib code, for that matter) from the console, there's nowhere for the plot to display. Unlike running python at the terminal, the shinylive.io web interface does not have a graphics device window which will open for plotnine. This is because the shinylive.io web interface is designed primarily for Shiny applications.

Here's a [example Shiny app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFV8BQpqigRpUFkwPbpq1fUbaANsTIQucXv0HCA5q9Q2yEqHBYTXOEYAfRIrM2h0YKUmAF4mJSwoQOCaKyVpAApVJlyEjgxiBTJUYuDPW2ywTzJlMABKPFV6iNVZGlY5ADc5TK5S7yYikuKJFj8WDlJ6xBy8gAFhgbnc+ak9OSwvTJaIPKZ26zId2b39vOkO+NRpDAARKDIoADE6WDhss-PzkBXv-7qXSgdA4UAARlY4HVEExgH9-gimHVAhs6HUml9EQjkTI5Oj4VjznVklD8ATCXliYF8ZiKfsqaSMXSAWAuCR4DTmd86mzGIzyXSeRB2fzaVyhSLOVyALpM8VER5wVyCbDQ2ECil1Z5wGBQSFSrmUsAAWT1osN9LAAEYALQAJgALAaLXU7QBWG1up1ksXMuput0AamdhrqABliCH5RGbca4KYfRajXGE3Kk3UABIcVxsKNY2UallA9KkmHAABsAAYJA7q0w3XWAMx1u11q0tt0Sd01ysF33nAC+At2CMucLAQJB4P1YGlcRMGAAworlSDCHrPhSx4DgaCIaTZUx1xRVxw-LFxyjZGj8EiUNTbxK+XVpcOBduFSeVS-5zclyvBA4dcrEyD9jyVb9ZwkcDT3PMCALoVVZ12AUpDIBQ6D2dwKmOS4fD8TIAA9Yh3Kd93RJhsBIic9QURkmBoDgrCsaiYMg+p6iYQMmECEIwh2VpIlQecxFQTI0FQaIODGbo5F2MAB2lIA) with your plot (and some associated shiny code around it)

This is the code for the app:

```py
from shiny import App, render, ui

import pandas as pd

from plotnine import ggplot, aes, geom_col

app_ui = ui.page_fluid(
    ui.output_plot("plt"),
)


def server(input, output, session):
    @output
    @render.plot()
    def plt():
        df = pd.DataFrame(
            {
                "variable": [
                    "gender",
                    "gender",
                    "age",
                    "age",
                    "age",
                    "income",
                    "income",
                    "income",
                    "income",
                ],
                "category": [
                    "Female",
                    "Male",
                    "1-24",
                    "25-54",
                    "55+",
                    "Lo",
                    "Lo-Med",
                    "Med",
                    "High",
                ],
                "value": [60, 40, 50, 30, 20, 10, 25, 25, 40],
            }
        )
        df["variable"] = pd.Categorical(
            df["variable"], categories=["gender", "age", "income"]
        )
        df["category"] = pd.Categorical(df["category"], categories=df["category"])

        return ggplot(df, aes(x="variable", y="value", fill="category")) + geom_col()


app = App(app_ui, server)
```
